# Generated by Django 4.2.1 on 2023-06-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_flashcardset_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
